# Generated by Django 4.2 on 2023-04-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_botusers_category_question_questiontype_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attempts',
            field=models.IntegerField(default=3),
        ),
    ]
