# Generated by Django 4.2 on 2023-04-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_question_question_type_useranswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('correct', 'correct'), ('incorrect', 'incorrect'), ('waiting', 'waiting')], default='wait', max_length=100, verbose_name='status'),
        ),
    ]
