# Generated by Django 4.2 on 2023-04-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='botusers',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='category_id'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('correct', 'correct'), ('incorrect', 'incorrect'), ('wait', 'wait')], default='wait', max_length=100, verbose_name='status'),
        ),
    ]
